# arguments for the API, settings for the email

[api]
# id which indicates which eth service is requesting the data
client_id = "ethz-wcms" # TODO: am I allowed to use this id?
# language; possible: ["en", "de"]
lang = "en"
# idk
rsfirst = 0
rssize = 1
# facility number
facility = 9